### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by phatnhse** [hoanghahuynh/TodoApp#4]
### Thank you for your submission hoanghahuynh.

 :smile: Everything looks good with the format of your submission.
- 100 hours! OMG! This is disgusting! Great work! You really pushed effort on doing the prework, I really appreciate that.
### Good stuffs
- Using `SQLite` and check condition before handling data is good.
- Nice to see you can handle `ListView`, `ArrayAdapter`.
- Good use `Bundle` and `Intent` to communicate 2 activities.
- Seem like you are similar to `Java Naming Convention`. Good job.
- Nice use `Toast`.
### Suggestions
- You should organize your code into sub-packages like adapters, activities, database... It will make your code clearly.
- Do you want to try `RecyclerView` and `CustomAdapter` instead of `ListView`?

In general, your code is good. Work harder.
### Questions
- Do you want to try some option features? It will be fun.

I'm here to be helpful. So if you have any question, please ask.

**Comment by hoanghahuynh** [comment]
Sure. And i will try to improve my App with more features. :) .
Thanks for your comment.
